apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: CI
          value: "false"
        - name: REACT_APP_API_URL
          value: "https://server.mern-stack.local.getwebstack.dev:9443/api"
        - name: WDS_SOCKET_PORT
          value: "9443"
        - name: WDS_SOCKET_HOST
          value: "client.mern-stack.local.getwebstack.dev"
        - name: WDS_SOCKET_PROTOCOL
          value: "wss"
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
      restartPolicy: Always
